
//User Actions

export const LOGIN_USER="LOGIN_USER"
export const REGISTER_USER="REGISTER_USER"
export const DELETE_USER="DELETE_USER"
export const RESET_PASSWORD="RESET_PASSWORD"
export const LOAD_USER="LOAD_USER"
export const ERROR_USER="ERROR_USER"
export const CURRENT_USER="CURRENT_USER"
export const LOGOUT_USER="LOUGOUT_USER"